---
- name: "Instalar dependências"
  ansible.builtin.apt:
    name:
      - "unzip"
      - "curl"
    state: "present"
    update_cache: true

- name: "Criar grupo e usuário vault"
  ansible.builtin.group:
    name: "{{ vault_group }}"
    state: "present"

- name: "Criar usuário vault"
  ansible.builtin.user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    shell: "/bin/false"
    system: true

- name: "Baixar Vault HashiCorp"
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest: "/tmp/vault_{{ vault_version }}.zip"
    mode: '0644'

- name: "Descompactar Vault binário"
  ansible.builtin.unarchive:
    src: "/tmp/vault_{{ vault_version }}.zip"
    dest: "{{ vault_install_path }}"
    remote_src: true
    mode: '0755'

- name: "Criar diretórios Vault"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0750'
  loop:
    - "{{ vault_config_dir }}"
    - "{{ vault_data_dir }}"

- name: "Copiar configuração Vault"
  ansible.builtin.template:
    src: "vault.hcl.j2"
    dest: "{{ vault_config_dir }}/vault.hcl"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0640'

- name: "Criar serviço systemd para Vault"
  ansible.builtin.template:
    src: "vault.service.j2"
    dest: "/etc/systemd/system/vault.service"
    mode: '0644'

- name: "Iniciar e habilitar serviço Vault"
  ansible.builtin.systemd:
    name: "vault"
    state: "started"
    enabled: true
    daemon_reload: true

- name: "Inicializar Vault (somente se ainda não estiver inicializado)"
  ansible.builtin.shell: |
    vault operator init -key-shares=1 -key-threshold=1 -format=json
  register: "vault_init_output"
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
  args:
    executable: "/bin/bash"
  changed_when: "'Unseal' in vault_init_output.stdout"
  failed_when: "vault_init_output.rc != 0 and 'Vault is already initialized' not in vault_init_output.stderr"

- name: "Salvar chaves geradas localmente (se inicializado agora)"
  ansible.builtin.copy:
    content: "{{ vault_init_output.stdout }}"
    dest: "./vault-init.json"
    mode: '0600'
  delegate_to: "localhost"
  become: false
  when: "'root_token' in vault_init_output.stdout"
