---
name: "Ansible CI/CD"

on:
  push:
    branches:
      - "main"  # ou sua branch principal
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

        
      - name: "Install dependencies"
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible-lint yamllint

      - name: "Run Ansible Lint"
        run: ansible-lint .

      - name: "Run Yamllint"
        run: |
          yamllint .

  deploy:
    needs: lint
    runs-on: runner-docker # runner local sem acessos externos
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Set up Python 3.x"
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: "Install Ansible"
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible

      - name: "Prepare SSH key"
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Adcione quando houver mais hosts
          ssh-keyscan -H "${{ secrets.ANSIBLE_HOST_1 }}" >> ~/.ssh/known_hosts
          ssh-keyscan -H "${{ secrets.ANSIBLE_HOST_2 }}" >> ~/.ssh/known_hosts

      - name: "Run Ansible Playbook"
        run: ansible-playbook -i inventory.ini playbook.yml -b
